service:
  name: myTypeScriptService
#app: your-app-name
#tenant: your-tenant-name

custom:
  webpack:
    includeModules: false # this is the default value, that means serverless webpack would not create the node_modules folder

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
